CI: azure
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- ignore_version
- pin_run_as_build
- extend_keys
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.11'
openssl: 1.1.1
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  openssl:
    max_pin: x.x.x
python: 3.7.* *_cpython
python_impl: cpython
r_base: '3.5'
target_platform: linux-64
zip_keys:
- - python
  - python_impl
