CONDA_BUILD_SYSROOT: ''
VERBOSE_AT: V=1
VERBOSE_CM: VERBOSE=1
_libgcc_mutex: 0.1 conda_forge
abseil_cpp: '20200225.2'
alsa_lib: 1.2.3
arb: '2.18'
arpack: 3.6.3
arrow_cpp: 0.17.1
bamtools: 2.5.1
blas_impl: openblas
boost: 1.70.0
boost_cpp: 1.70.0
bzip2: '1'
c_compiler: gcc
c_compiler_version: '7'
cairo: '1.16'
cfitsio: '3.470'
cgo_compiler: go-cgo
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cuda_compiler: nvcc
cuda_compiler_version: '10.1'
cudnn: 7.6.5
curl: '7'
cxx_compiler: gxx
cxx_compiler_version: '7'
dbus: '1'
docker_image: condaforge/linux-anvil-cuda:10.1
expat: '2.2'
extend_keys:
- pin_run_as_build
- ignore_build_only_deps
- extend_keys
- ignore_version
ffmpeg: '4.2'
fftw: '3'
flann: 1.9.1
fmt: '7'
fontconfig: '2.13'
fortran_compiler: gfortran
fortran_compiler_version: '7'
freetype: 2.9.1
gdal: '3.0'
gdk_pixbuf: 2.36.12
geos: 3.8.1
geotiff: '1.6'
gf2x: '1.2'
gflags: '2.2'
giflib: '5.2'
glew: '2.1'
glib: '2.58'
glog: 0.4.0
glpk: '4.65'
gmp: '6'
gnuradio_core: 3.8.2
go_compiler: go-nocgo
google_cloud_cpp: '1.16'
google_cloud_cpp_common: 0.25.0
googleapis_cpp: '0.10'
graphviz: '2.40'
grpc_cpp: '1.30'
gsl: '2.6'
gst_plugins_base: 1.14.4
gstreamer: 1.14.4
harfbuzz: '2'
hdf4: '4.2'
hdf5: 1.10.5
htslib: '1.10'
icu: '64.2'
ignore_build_only_deps:
- numpy
- python
isl: '0.22'
jasper: 1.900.1
jpeg: '9'
json_c: '0.13'
jsoncpp: 1.8.4
kealib: '1.4'
krb5: '1.16'
libarchive: '3.3'
libblas: 3.8 *netlib
libblitz: '0.10'
libcblas: 3.8 *netlib
libcrc32c: '1.1'
libcurl: '7'
libdap4: 3.20.2
libevent: 2.1.10
libffi: '3.2'
libgdal: '3.0'
libiconv: '1.16'
libjpeg_turbo: '2'
libkml: '1.3'
liblapack: 3.8.0 *netlib
liblapacke: 3.8.0 *netlib
libmatio: '1.5'
libnetcdf: 4.7.4
libpcap: '1.9'
libpng: '1.6'
libprotobuf: '3.11'
librdkafka: 0.11.5
librsvg: '2'
libsecret: '0.18'
libspatialindex: 1.9.3
libssh2: '1'
libsvm: '3.21'
libtiff: 4.1.0
libunwind: '1.2'
libuuid: 2.32.1
libv8: 8.4.371
libwebp: '1.1'
libwebp_base: '1.1'
libxml2: '2.9'
lua: '5'
lz4_c: 1.9.2
lzo: '2'
metis: '5.1'
mimalloc: 1.6.3
mkl: '2019'
mpfr: '4'
mpich: '3.3'
mumps_mpi: '5.2'
mumps_seq: '5.2'
nccl: 2.4.6.1
ncurses: '6.2'
netcdf_cxx4: '4.3'
netcdf_fortran: '4.5'
nettle: '3.4'
nlopt: 2.6.*
nspr: '4'
nss: '3'
ntl: 11.4.3
numpy: '1.16'
occt: '7.4'
openblas: 0.3.*
openjpeg: '2.3'
openmpi: '4.0'
openssl: 1.1.1
openturns: '1.15'
pango: '1.42'
pari: '2.11'
perl: 5.26.2
petsc: '3.12'
petsc4py: '3.12'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
  arpack:
    max_pin: x.x.x
  boost:
    max_pin: x.x.x
  boost-cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  cairo:
    max_pin: x.x
  cudnn:
    max_pin: x
    min_pin: x.x
  curl:
    max_pin: x
  dbus:
    max_pin: x
  expat:
    max_pin: x.x
  ffmpeg:
    max_pin: x.x
  fftw:
    max_pin: x
  flann:
    max_pin: x.x.x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  gdal:
    max_pin: x.x
  gdk_pixbuf:
    max_pin: x.x.x
  geotiff:
    max_pin: x.x.x
  glew:
    max_pin: x.x
  glpk:
    max_pin: x.x
  gmp:
    max_pin: x
  graphviz:
    max_pin: x
  harfbuzz:
    max_pin: x
  hdf4:
    max_pin: x.x
  icu:
    max_pin: x
  isl:
    max_pin: x.x
  jasper:
    max_pin: x
  jpeg:
    max_pin: x
  libjpeg_turbo:
    max_pin: x
  json-c:
    max_pin: x.x
  jsoncpp:
    max_pin: x.x.x
  kealib:
    max_pin: x.x
  krb5:
    max_pin: x.x
  libblitz:
    max_pin: x.x
  libcurl:
    max_pin: x
  libevent:
    max_pin: x.x.x
  libffi:
    max_pin: x.x
  libgdal:
    max_pin: x.x
  libiconv:
    max_pin: x.x
  libkml:
    max_pin: x.x
  libmatio:
    max_pin: x.x
  libpcap:
    max_pin: x.x
  libpng:
    max_pin: x.x
  librdkafka:
    max_pin: x.x.x
  librsvg:
    max_pin: x
  libsvm:
    max_pin: x.x
  libunwind:
    max_pin: x.x
  libtiff:
    max_pin: x
  libxml2:
    max_pin: x.x
  libuuid:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  lzo:
    max_pin: x
  metis:
    max_pin: x.x
  mkl:
    max_pin: x
  mpfr:
    max_pin: x
  ncurses:
    max_pin: x.x
  netcdf-cxx4:
    max_pin: x.x
  netcdf-fortran:
    max_pin: x.x
  nettle:
    max_pin: x.x
  nlopt:
    max_pin: x.x.x
  nss:
    max_pin: x
  nspr:
    max_pin: x
  occt:
    max_pin: x.x
  openturns:
    max_pin: x.x
  openjpeg:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  pango:
    max_pin: x.x
  perl:
    max_pin: x.x.x
  pixman:
    max_pin: x.x
  poppler:
    max_pin: x.x
  qt:
    max_pin: x.x
  readline:
    max_pin: x
  sox:
    max_pin: x.x.x
  sqlite:
    max_pin: x
  tk:
    max_pin: x.x
  tiledb:
    max_pin: x.x
  vlfeat:
    max_pin: x.x.x
  vtk:
    max_pin: x.x.x
  xz:
    max_pin: x.x
  zeromq:
    max_pin: x.x
  zlib:
    max_pin: x.x
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
pixman: '0.38'
poppler: 0.67.0
proj: 7.1.0
ptscotch: 6.0.8
python: 3.8.*  *_cpython
python_impl: cpython
qt: '5.12'
r_base: 4.0.*
re2: 2020.08.01
readline: '8.0'
rocksdb: '6.10'
root_base: '6.20'
ruby: '2.5'
rust_compiler: rust
rust_compiler_version: 1.40.0
scotch: 6.0.8
singular: 4.1.2
slepc: '3.12'
slepc4py: '3.12'
snappy: '1'
soapysdr: '0.7'
sox: 14.4.2
sqlite: '3'
suitesparse: '5.6'
target_goarch: amd64
target_gobin: ${PREFIX}/bin/
target_goexe: ''
target_goos: linux
target_platform: linux-64
tiledb: '2.0'
tk: '8.6'
uhd: 3.15.0
vlfeat: 0.9.20
vtk: 8.2.0
x264: 1!152.*
xerces_c: '3.2'
xrootd: '4.12'
xz: '5.2'
zeromq: 4.3.2
zip_keys:
- - python
- - cuda_compiler_version
  - docker_image
zlib: '1.2'
zstd: '1.4'
