CI: azure
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- ignore_build_only_deps
- pin_run_as_build
- extend_keys
- ignore_version
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
krb5: 1.17.1
libssh2: '1'
lua: '5'
numpy: '1.11'
openssl: 1.1.1
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  krb5:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  perl:
    max_pin: x.x.x
  zlib:
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
zlib: '1.2'
