VERBOSE_AT: V=1
VERBOSE_CM: VERBOSE=1
arpack: '3.5'
bamtools: 2.4.1
blas_impl: openblas
boost: 1.66.0
boost_cpp: 1.66.0
bzip2: '1'
c_compiler: toolchain_c
cairo: '1.14'
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
curl: '7.59'
cxx_compiler: toolchain_cxx
dbus: '1'
expat: '2.2'
ffmpeg: '4.0'
flann: 1.9.1
fontconfig: '2.13'
fortran_compiler: toolchain_fort
freetype: 2.8.1
gdal: '2.2'
geos: 3.6.2
giflib: '5.1'
glew: 2.0.0
glib: '2.55'
glpk: '4.65'
gmp: '6'
gsl: '2.2'
gst_plugins_base: '1.12'
gstreamer: '1.12'
harfbuzz: '1.7'
hdf4: '4.2'
hdf5: 1.10.2
htslib: '1.7'
icu: '58'
ignore_build_only_deps: python
isl: '0.19'
jpeg: '9'
json_c: '0.12'
jsoncpp: 1.8.1
krb5: '1.14'
libblitz: '0.10'
libdap4: '3.19'
libevent: 2.0.22
libffi: '3.2'
libgdal: '2.2'
libiconv: '1.15'
libkml: '1.3'
libmatio: '1.5'
libnetcdf: '4.5'
libpcap: '1.8'
libpng: 1.6.34
libprotobuf: '3.5'
librdkafka: 0.9.4
libssh2: '1.8'
libsvm: '3.21'
libtiff: 4.0.9
libunwind: '1.2'
libwebp: '0.5'
libxml2: '2.9'
lua: '5'
lz4_c: 1.8.1
lzo: '2'
metis: '5.1'
mkl: '2018'
mpfr: '4'
ncurses: '5.9'
netcdf_cxx4: '4.3'
netcdf_fortran: '4.4'
nettle: '3.3'
numpy: '1.9'
openblas: 0.2.20
openjpeg: '2.3'
openssl: 1.0.2
pango: '1.40'
perl: '5.26'
pin_run_as_build:
  python: {min_pin: x.x, max_pin: x.x}
  r-base: {max_pin: x.x.x}
  arpack: {max_pin: x.x}
  boost: {max_pin: x.x.x}
  boost-cpp: {max_pin: x.x.x}
  bzip2: {max_pin: x}
  cairo: {max_pin: x.x}
  curl: {max_pin: x}
  dbus: {max_pin: x}
  expat: {max_pin: x.x}
  ffmpeg: {max_pin: x.x}
  flann: {max_pin: x.x.x}
  fontconfig: {max_pin: x}
  freetype: {max_pin: x.x}
  gsl: {max_pin: x.x}
  gstreamer: {max_pin: x.x}
  gst-plugins-base: {max_pin: x.x}
  gdal: {max_pin: x.x}
  geos: {max_pin: x.x.x}
  giflib: {max_pin: x.x}
  glew: {max_pin: x.x}
  glib: {max_pin: x.x}
  glpk: {max_pin: x.x}
  gmp: {max_pin: x}
  harfbuzz: {max_pin: x.x}
  hdf4: {max_pin: x.x}
  hdf5: {max_pin: x.x.x}
  icu: {max_pin: x}
  isl: {max_pin: x.x}
  jpeg: {max_pin: x}
  json-c: {max_pin: x.x}
  jsoncpp: {max_pin: x.x.x}
  krb5: {max_pin: x.x}
  libblitz: {max_pin: x.x}
  libdap4: {max_pin: x.x}
  libevent: {max_pin: x.x.x}
  libffi: {max_pin: x.x}
  libgdal: {max_pin: x.x}
  libiconv: {max_pin: x.x}
  libkml: {max_pin: x.x}
  libmatio: {max_pin: x.x}
  libnetcdf: {max_pin: x.x}
  libpcap: {max_pin: x.x}
  libpng: {max_pin: x.x}
  libprotobuf: {max_pin: x.x}
  librdkafka: {max_pin: x.x.x}
  libssh2: {max_pin: x.x}
  libsvm: {max_pin: x.x}
  libunwind: {max_pin: x.x}
  libtiff: {max_pin: x}
  libwebp: {max_pin: x.x}
  libxml2: {max_pin: x.x}
  lz4-c: {max_pin: x.x.x}
  lzo: {max_pin: x}
  metis: {max_pin: x.x}
  mkl: {max_pin: x}
  mpfr: {max_pin: x}
  ncurses: {max_pin: x.x}
  netcdf-cxx4: {max_pin: x.x}
  netcdf-fortran: {max_pin: x.x}
  nettle: {max_pin: x.x}
  openblas: {max_pin: x.x.x}
  openjpeg: {max_pin: x.x}
  openssl: {max_pin: x.x.x}
  pango: {max_pin: x.x}
  perl: {max_pin: x.x}
  pixman: {max_pin: x.x}
  poppler: {max_pin: x.x}
  proj4: {max_pin: x.x.x}
  pyqt: {max_pin: x.x}
  qt: {max_pin: x.x}
  readline: {max_pin: x.x}
  snappy: {max_pin: x.x.x}
  sox: {max_pin: x.x.x}
  sqlite: {max_pin: x}
  sundials: {max_pin: x.x}
  tk: {max_pin: x.x}
  vc: {max_pin: x}
  vlfeat: {max_pin: x.x.x}
  xerces-c: {max_pin: x.x.x}
  xz: {max_pin: x.x}
  zeromq: {max_pin: x.x.x}
  zlib: {max_pin: x.x}
  zstd: {max_pin: x.x.x}
  htslib: {max_pin: x.x}
  bamtools: {max_pin: x.x.x}
pixman: '0.34'
poppler: '0.61'
proj4: 4.9.3
pyqt: '5.6'
python: '2.7'
qt: '5.6'
r_base: 3.4.1
readline: '7.0'
snappy: 1.1.7
sox: 14.4.2
sqlite: '3'
sundials: '2.7'
target_platform: linux-64
tk: '8.6'
vlfeat: 0.9.20
xerces_c: 3.2.0
xz: '5.2'
zeromq: 4.2.1
zip_keys:
- [pyqt, qt]
- [python]
zlib: '1.2'
zstd: 1.3.3
